name: Patch and release youtube

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      youtube_beta_url:
        required: true
        type: string
      youtube_latest_url:
        required: true
        type: string
      youtube_fit_url:
        required: true
        type: string
      cli_url:
        required: true
        type: string
      patches_url:
        required: true
        type: string
      integrations_url:
        required: true
        type: string
      youtube_beta_version:
        required: true
        type: string
      youtube_latest_version:
        required: true
        type: string
      youtube_fit_version:
        required: true
        type: string
      cli_version:
        required: true
        type: string
      patches_version:
        required: true
        type: string
      integrations_version:
        required: true
        type: string
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Temporary Directory Structure
        run: |
          mkdir -p .tmp/youtube
          mkdir -p .tmp/tools
          mkdir -p .tmp/artifacts
      - name: Download Youtube and ReVanced tools
        run: |
          # Youtube
          useragent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
          curl -sL -A $useragent -o .tmp/youtube/beta.apk ${{inputs.youtube_beta_url}}
          curl -sL -A $useragent -o .tmp/youtube/latest.apk ${{inputs.youtube_latest_url}}
          curl -sL -A $useragent -o .tmp/youtube/fit.apk ${{inputs.youtube_fit_url}}
          # Tools
          curl -sL -A $useragent -o .tmp/tools/cli.jar ${{inputs.cli_url}}
          curl -sL -A $useragent -o .tmp/tools/patches.jar ${{inputs.patches_url}}
          curl -sL -A $useragent -o .tmp/tools/integrations.apk ${{inputs.integrations_url}}
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Patch youtube fit version
        run: |
          java \
            -jar .tmp/tools/cli.jar \
              --apk     .tmp/youtube/fit.apk \
              --bundles .tmp/tools/patches.jar \
              --merge   .tmp/tools/integrations.apk \
              -e enable-debugging \
              -e custom-playback-speed \
              -e hide-infocard-suggestions \
              -e hide-time-and-seekbar \
              -e old-quality-layout \
              -e enable-wide-searchbar \
              -e disable-fullscreen-panels \
              -e hide-autoplay-button \
              -e hide-video-buttons \
              -e hide-email-address \
              -e tablet-mini-player \
              -e disable-auto-player-popup-panels \
              --rip-lib x86_64 \
              --rip-lib x86 \
              --rip-lib arm64-v8a \
              --out ".tmp/artifacts/YouTube ${{ input.youtube_fit_version }}.apk" \
              --clean

      - name: Patch latest youtube
        run: |
          java \
            -jar .tmp/tools/cli.jar \
              --apk     .tmp/youtube/latest.apk \
              --bundles .tmp/tools/patches.jar \
              --merge   .tmp/tools/integrations.apk \
              --experimental \
              -e enable-debugging \
              -e custom-playback-speed \
              -e hide-infocard-suggestions \
              -e hide-time-and-seekbar \
              -e old-quality-layout \
              -e enable-wide-searchbar \
              -e disable-fullscreen-panels \
              -e hide-autoplay-button \
              -e hide-video-buttons \
              -e hide-email-address \
              -e tablet-mini-player \
              -e disable-auto-player-popup-panels \
              --rip-lib x86_64 \
              --rip-lib x86 \
              --rip-lib arm64-v8a \
              --out ".tmp/artifacts/Youtube ${{ input.youtube_latest_version }}.apk" \
              --clean
    
      - name: Patch beta youtube version
        run: |
          java \
            -jar .tmp/tools/cli.jar \
              --apk     .tmp/youtube/beta.apk \
              --bundles .tmp/tools/patches.jar \
              --merge   .tmp/tools/integrations.apk \
              --experimental \
              -e enable-debugging \
              -e custom-playback-speed \
              -e hide-infocard-suggestions \
              -e hide-time-and-seekbar \
              -e old-quality-layout \
              -e enable-wide-searchbar \
              -e disable-fullscreen-panels \
              -e hide-autoplay-button \
              -e hide-video-buttons \
              -e hide-email-address \
              -e tablet-mini-player \
              -e disable-auto-player-popup-panels \
              --rip-lib x86_64 \
              --rip-lib x86 \
              --rip-lib arm64-v8a \
              --out ".tmp/artifacts/Youtube ${{ input.youtube_beta_version }}.apk" \
              --clean

      - name: Generate release notes
        run: |
          env \
            revanced_cli_version=${{ input.cli_version }} \
            recanced_patches_version=${{ input.patches_version }} \
            revanced_integrations_version=${{ input.integrations_version }} \
            youtube_beta_version=${{ input.youtube_beta_version }}
            youtube_latest_version=${{ input.youtube_latest_version }}
            youtube_fit_version=${{ input.youtube_fit_version }}
            envsubst < ReleaseNotesTemplate.md > .tmp/ReleaseNotes.md

      - name: Make tag
        id: make-tag
        run: |
          tag="$(date +%F)-$(git rev-parse --short HEAD)"
          git tag "$tag"
          echo "::set-output name=tag-name::${tag}"
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          bodyFile: .tmp/ReleaseNotes.md
          artifacts: .tmp/artifacts/*.apk
          tag: ${{ steps.make-tag.outputs.tag-name }}
          token: ${{ github.token }}
          allowUpdates: true
