name: Patch

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      youtube_beta_url:
        required: true
        type: string
      youtube_latest_url:
        required: true
        type: string
      youtube_fit_url:
        required: true
        type: string
      cli_url:
        required: true
        type: string
      patches_url:
        required: true
        type: string
      integrations_url:
        required: true
        type: string
      youtube_beta_version:
        required: true
        type: string
      youtube_latest_version:
        required: true
        type: string
      youtube_fit_version:
        required: true
        type: string
      cli_version:
        required: true
        type: string
      patches_version:
        required: true
        type: string
      integrations_version:
        required: true
        type: string
jobs:
  download:
    name: Download and patch
    runs-on: ubuntu-latest
    env:
      patches: 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Temporary Directory Structure
        run: |
          mkdir -p .tmp/youtube
          mkdir -p .tmp/tools
          mkdir -p .tmp/artifacts
      - name: Download Youtube and ReVanced tools
        run: |
          # Youtube
          useragent='Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)'
          curl -sL -A "$useragent" -o .tmp/youtube/beta.apk       '${{inputs.youtube_beta_url}}'
          curl -sL -A "$useragent" -o .tmp/youtube/latest.apk     '${{inputs.youtube_latest_url}}'
          curl -sL -A "$useragent" -o .tmp/youtube/fit.apk        '${{inputs.youtube_fit_url}}'
          # Tools
          curl -sL -A "$useragent" -o .tmp/tools/cli.jar          '${{inputs.cli_url}}'
          curl -sL -A "$useragent" -o .tmp/tools/patches.jar      '${{inputs.patches_url}}'
          curl -sL -A "$useragent" -o .tmp/tools/integrations.apk '${{inputs.integrations_url}}'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Specify patches
        id: patches
        run: |
          echo list=$(while read -r line; do [ "${line:0:1}" = "#" ] && continue; echo "-i"; echo "$line"; done < ./patches) >> $GITHUB_OUTPUT

      - name: Patch youtube fit version
        run: |
          java                                                    \
            -jar .tmp/tools/cli.jar                               \
              --apk     .tmp/youtube/fit.apk                      \
              --bundle .tmp/tools/patches.jar                    \
              --merge   .tmp/tools/integrations.apk               \
              --exclusive                                         \
              ${{ steps.patches.outputs.list }}                   \
              --out ".tmp/artifacts/YouTube-${{ inputs.youtube_fit_version }}.apk"

      - name: Patch latest youtube
        run: |
          java                                                    \
            -jar .tmp/tools/cli.jar                               \
              --apk     .tmp/youtube/latest.apk                   \
              --bundle .tmp/tools/patches.jar                    \
              --merge   .tmp/tools/integrations.apk               \
              --experimental                                      \
              --exclusive                                         \
              ${{ steps.patches.outputs.list }}                   \
              --out ".tmp/artifacts/YouTube-${{ inputs.youtube_latest_version }}.apk"

      - name: Patch beta youtube version
        run: |
          java                                                    \
            -jar .tmp/tools/cli.jar                               \
              --apk     .tmp/youtube/beta.apk                     \
              --bundle .tmp/tools/patches.jar                    \
              --merge   .tmp/tools/integrations.apk               \
              --experimental                                      \
              --exclusive                                         \
              ${{ steps.patches.outputs.list }}                   \
              --out ".tmp/artifacts/YouTube-${{ inputs.youtube_beta_version }}.apk"

      - name: Generate release notes
        run: |
          env \
            cli_version=${{ inputs.cli_version }} \
            patches_version=${{ inputs.patches_version }} \
            integrations_version=${{ inputs.integrations_version }} \
            youtube_beta_version=${{ inputs.youtube_beta_version }} \
            youtube_latest_version=${{ inputs.youtube_latest_version }} \
            youtube_fit_version=${{ inputs.youtube_fit_version }} \
            envsubst < ReleaseNotesTemplate.md > .tmp/ReleaseNotes.md

      - name: Make tag
        id: make-tag
        run: |
          tag="$(date +%F)-$(git rev-parse --short HEAD)"
          git tag "$tag"
          echo tag-name=$tag >> $GITHUB_OUTPUT
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          bodyFile: .tmp/ReleaseNotes.md
          artifacts: .tmp/artifacts/*.apk
          tag: ${{ steps.make-tag.outputs.tag-name }}
          token: ${{ github.token }}
          allowUpdates: true
