name: Patch and release youtube

on:
  workflow_dispatch:
  push:
    paths:
      - 'dependencies/*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      # set up envirenment
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      # create temporary directory structure
      - name: build temporary directory structure
        run: |
          mkdir .tmp
          mkdir .tmp/youtube
          mkdir .tmp/youtube/latest-cache
          mkdir .tmp/youtube/beta-cache
          mkdir .tmp/youtube/recommended-cache
          mkdir .tmp/artifacts
      # download youtube and microg
      - name: download youtube stable, beta and recommended versions
        run: |
          useragent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
          wget \
            --user-agent="$useragent" \
            `node scrape-youtube-download-link.mjs 17.39.35` \
            -O .tmp/youtube/latest.apk
          wget \
            --user-agent="$useragent" \
            `node scrape-youtube-download-link.mjs 17.36.37` \
            -O .tmp/youtube/recommended.apk
          wget \
            --user-agent="$useragent" \
            `node scrape-youtube-download-link.mjs 17.40.35` \
            -O .tmp/youtube/beta.apk

      # download build dependencies
      - name: download ReVanced CLI
        run: |
          curl -sL `jq -r '.download_url' dependencies/revanced-cli.json` \
            -o .tmp/revanced-cli.jar
          curl -sL `jq -r '.download_url' dependencies/revanced-patches.json` \
            -o .tmp/revanced-patches.jar
          curl -sL `jq -r '.download_url' dependencies/revanced-integrations.json` \
            -o .tmp/revanced-integrations.apk

      # start patching
      - name: Patch recommended youtube version
        run: |
          java \
          -jar .tmp/revanced-cli.jar \
          --apk .tmp/youtube/recommended.apk \
          --bundles .tmp/revanced-patches.jar \
          --merge .tmp/revanced-integrations.apk \
          --experimental \
          -e enable-debugging \
          -e custom-playback-speed \
          -e hide-infocard-suggestions \
          -e hide-time-and-seekbar \
          -e old-quality-layout \
          -e enable-wide-searchbar \
          -e disable-fullscreen-panels \
          -e hide-autoplay-button \
          -e hide-video-buttons \
          -e hide-email-address \
          -e tablet-mini-player \
          -e disable-auto-player-popup-panels \
          --clean \
          --temp-dir .tmp/youtube/recommemded-cache/ \
          --out .tmp/artifacts/youtube-revanced-recommended.apk"

      - name: Patch latest youtube version
        run: |
          java \
          -jar .tmp/revanced-cli.jar \
          --apk .tmp/youtube/latest.apk \
          --bundles .tmp/revanced-patches.jar \
          --merge .tmp/revanced-integrations.apk \
          --experimental \
          -e enable-debugging \
          -e custom-playback-speed \
          -e hide-infocard-suggestions \
          -e hide-time-and-seekbar \
          -e old-quality-layout \
          -e enable-wide-searchbar \
          -e disable-fullscreen-panels \
          -e hide-autoplay-button \
          -e hide-video-buttons \
          -e hide-email-address \
          -e tablet-mini-player \
          -e disable-auto-player-popup-panels \
          --clean \
          --temp-dir .tmp/youtube/latest-cache/ \
          --out .tmp/artifacts/youtube-revanced-latest.apk

      - name: Patch beta youtube version
        run: |
          java \
          -jar .tmp/revanced-cli.jar \
          --apk .tmp/youtube/beta.apk \
          --bundles .tmp/revanced-patches.jar \
          --merge .tmp/revanced-integrations.apk \
          --experimental \
          -e enable-debugging \
          -e custom-playback-speed \
          -e hide-infocard-suggestions \
          -e hide-time-and-seekbar \
          -e old-quality-layout \
          -e enable-wide-searchbar \
          -e disable-fullscreen-panels \
          -e hide-autoplay-button \
          -e hide-video-buttons \
          -e hide-email-address \
          -e tablet-mini-player \
          -e disable-auto-player-popup-panels \
          --clean \
          --temp-dir .tmp/youtube/beta-cache/ \
          --out .tmp/artifacts/youtube-revanced-beta.apk

      - name: Generate release notes
        run: |
          env \
            cli=`jq '.version' dependencies/revanced-cli.json` \
            patches=`jq '.version' dependencies/revanced-patches.json` \
            integrations=`jq '.version' dependencies/revanced-integrations.json` \
            envsubst < ReleaseNotesTemplate.md > ReleaseNotes.md

      - name: make tag
        id: make-tag
        run: |
          tag=`date +%F`
          git tag "$tag"
          echo "::set-output name=tag::${tag}"
      - name: Uploading
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          bodyFile: ReleaseNotes.md
          artifacts: .tmp/artifacts/*
          tag: ${{ steps.make-tag.outputs.tag }}
