name: Update

on:
  # tiggers manually
  workflow_dispatch:
  # triggers every 2 hours
  schedule:
    - cron: '0 0/2 * * *'

jobs:
  check:
    name: Check for updates
    runs-on: ubuntu-latest
    outputs:
      shouldUpdate: "${{ steps.compare.outputs.isModified }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Query
        run: |
          mkdir -p build-tools
          revanced_endpoint=https://releases.rvcd.win/tools
          revanced_tools_data=$(jq -r .tools <<< "$(curl -sL $revanced_endpoint)")
          jq <<< $revanced_tools_data > build-tools/vanced-microg.json \
            '.[0]|{version, download_url:.browser_download_url}'
          jq <<< $revanced_tools_data > build-tools/revanced-cli.json \
            '.[1]|{version, download_url:.browser_download_url}'
          jq <<< $revanced_tools_data > build-tools/revanced-patches.json \
            '.[4]|{version, download_url:.browser_download_url}'
          jq <<< $revanced_tools_data > build-tools/revanced-integrations.json \
            '.[5]|{version, download_url:.browser_download_url}'
          github_endpoint=https://api.github.com
          jhc_cli_data=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "${github_endpoint}/repos/j-hc/revanced-cli/releases/latest")
          jq <<< $jhc_cli_data > build-tools/jhc-revanced-cli.json \
            '{version:.name, download_url:.assets.[0].browser_download_url}'

      - name: Compare
        id: compare
        run: echo ::set-output name=isModified::$([ -z "`git status --porcelain`" ] && echo "no" || echo "yes")

      - name: Commit the updates
        if: steps.compare.outputs.isModified == 'yes'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'build-tools'
          message: automated update
          push: true
          
  build:
    needs: check
    if: needs.check.outputs.shouldUpdate == 'yes'
    uses: ./.github/workflows/build.yml
